version: "3.7"
services:
  centreon-central:
    image: paulhiv/centreon:1.0
    # enabe cgroups to access to systemd
    privileged: true
#    command: "/entrypoint.sh"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "centreon-engine:/usr/share/centreon-engine"
      - "Centreon-Engine-var-lib:/var/lib/centreon-engine"
      - "Centreon-Engine-Connector:/usr/lib64/centreon-connector"
      - "Centreon-Engine-Library:/usr/lib64/centreon-engine"
      - "Centreon-Plugins:/usr/lib/centreon/plugins/"
    ports:
      - "80:80"
    networks:
      - centreon



volumes:
  centreon-engine:
  Centreon-Engine-var-lib:
  Centreon-Engine-Connector:
  Centreon-Engine-Library:
  Centreon-Plugins:
networks:
  centreon: