#!/usr/bin/expect -f
set timeout -1
spawn /usr/share/centreon/bin/registerServerTopology.sh -u admin -t poller -h centreon-poller -n remote-bdd
expect "centreon-poller: please enter your password:"
send -- "azerty\n"
expect "Which IP do you want to use as CURRENT NODE IP ?.*"
send -- "1\n"
expect "Do you want to register this server with those informations ?.*"
send -- "y\n"
expect "<CURRENT_NODE_ADDRESS> : Please enter your username*."
send -- "admin\n"
expect "<CURRENT_NODE_ADDRESS> : Please enter your password.*:"
send -- "azerty\n"
expect "<CURRENT_NODE_ADDRESS> : Protocol.*"
send -- "\n"
expect "<CURRENT_NODE_ADDRESS> : Port.*"
send -- "\n"
expect "<CURRENT_NODE_ADDRESS> : centreon root folder.*"
send -- "\n"
expect "Are you using a proxy ?.*"
send -- "n\n"
expect eof